run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck       # Check for unchecked errors
    - gosimple       # Simplify code
    - govet          # Standard Go vet
    - ineffassign    # Detect ineffectual assignments
    - staticcheck    # Many useful static analysis checks
    - typecheck      # Type checking
    - unused         # Find unused variables, functions, etc.
    
    # Additional useful linters
    - gofmt          # Check formatting
    - goimports      # Check imports formatting
    - misspell       # Check for misspelled words
    - unconvert      # Remove unnecessary conversions
    - unparam        # Find unused function parameters
    - gocritic       # Various code quality checks
    - gocyclo        # Check cyclomatic complexity
    - revive         # Replacement for golint
    
  disable:
    - deadcode       # Deprecated in favor of unused
    - varcheck       # Deprecated in favor of unused
    - structcheck    # Deprecated in favor of unused

linters-settings:
  gocyclo:
    min-complexity: 15
  
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - whyNoLint  # Allow missing linter disable explanations

  revive:
    rules:
      - name: exported
        arguments: [true]

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec

  # Maximum number of issues to show
  max-issues-per-linter: 0
  max-same-issues: 0