name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Check formatting
        run: |
          if [ "$(gofmt -l .)" != "" ]; then
            echo "Code is not formatted. Run 'gofmt -w .' to fix."
            gofmt -l .
            exit 1
          fi

      - name: Check go mod tidy
        run: |
          go mod tidy
          if ! git diff --quiet go.mod go.sum; then
            echo "go.mod or go.sum is not tidy. Run 'go mod tidy' to fix."
            git diff go.mod go.sum
            exit 1
          fi

      - name: Build
        run: go build -v ./...

      - name: Run linting with go vet
        run: go vet ./...

      - name: Run tests with coverage
        run: go test -v -coverprofile=coverage.out ./...
